name: instabug_flutter
version: 10.0.0
description: >-
  Instabug is an in-app feedback and bug reporting tool for mobile apps. 
  With just a simple shake, your users or beta testers can report bugs or 
  send in-app feedback and the SDK will capture an environment snapshot of 
  your user's device including all console logs, server-side network requests 
  and bug reproduction steps compiling all these details in one organised dashboard
  to help you debug and fix bugs faster.
homepage: https://github.com/Instabug/Instabug-Flutter#readme
documentation: https://github.com/Instabug/Instabug-Flutter#readme

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

flutter:
  plugin:
    platforms:
      android:
        package: com.instabug.instabugflutter
        pluginClass: InstabugFlutterPlugin
      ios:
        pluginClass: InstabugFlutterPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  # Flutter versions prior to 1.12 did not support the
  # flutter.plugin.platforms map.
  flutter: ">=2.0.0 <3.0.0"
